server:
  port: 9036

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.119.175:3306/flink?characterEncoding=utf-8&useSSL=false
    username: root
    password: jackybian

mybatis:
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true